konyvtar/konyvtar/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^nyilvantartas/', include('nyilvantartas.urls')),
    url(r'^admin/', admin.site.urls),
]

konyvtar/nyilvantartas/urls.py
from django.conf.urls import url

from . import views

app_name = 'nyilvantartas'
urlpatterns = [
    # ex: /nyilvantartas/
    url(r'^$', views.index, name='index'),
    # ex: /nyilvantartas/5/
    url(r'^(?P<lending_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /nyilvantartas/kolcsonzes/
    url(r'^kolcsonzes/$', views.lending, name='lending'),
]

konyvtar/nyilvantartas/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
	first_name = models.CharField(max_length=60)
	last_name = models.CharField(max_length=60, default='', blank=True)
	birth_year = models.IntegerField(null=True, blank=True)
	birth_place = models.CharField(max_length=60, default='', blank=True)
	death_year = models.IntegerField(null=True, blank=True)
	death_place = models.CharField(max_length=60, default='', blank=True)

	def __str__(self):
		name = self.first_name
		if self.last_name:
			name += ' {0}'.format(self.last_name)
		return name


class Book(models.Model):
	author = models.ManyToManyField(Author)
	title = models.CharField(max_length=60)
	publisher = models.CharField(max_length=60, default='', blank=True)
	year = models.IntegerField()
	btype = models.CharField('type of lending', max_length=2, choices=(
		('1m', '1 hónapos kölcsönzés'),
		('1w', '1 hetes kölcsönzés'),
		('0w', 'nem kölcsönözhető')
		), default='1m')

	def __str__(self):
		return self.title


class User(models.Model):
	first_name = models.CharField(max_length=60)
	last_name = models.CharField(max_length=60)
	birth_year = models.IntegerField()
	birth_place = models.CharField(max_length=60)
	work_place = models.CharField(max_length=60)
	email = models.EmailField(max_length=60)
	phone = models.CharField(max_length=60)

	def __str__(self):
		return '{0} {1}'.format(self.first_name, self.last_name)


class Lending(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	lending_date = models.DateTimeField()

	def __str__(self):
		return '{0} | {1} | {2}'.format(self.user, self.book, self.lending_date)

konyvtar/nyilvantartas/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Book, User, Lending
from datetime import datetime


def index(request):
	latest_lending_list = Lending.objects.order_by('-lending_date')[:10]
	context = {
		'latest_lending_list': latest_lending_list,
	}
	return render(request, 'nyilvantartas/index.html', context)


def lending(request):
	if request.POST and request.POST['book'] and request.POST['user']:# and request.POST['lending_date']:
		user = User.objects.get(pk=request.POST['user'])
		book = Book.objects.get(pk=request.POST['book'])
		if user and book:
			lending = Lending(
				user=user,
				book=book,
				lending_date=datetime.utcnow().isoformat(' ')[:-7]
				#lending_date=request.POST['lending_date']
			)
			lending.save()
		return HttpResponseRedirect(reverse('nyilvantartas:index'))
	else:
		users = User.objects.all()
		books = Book.objects.all()
		context = {
			'users': users,
			'books': books
		}
		return render(request, 'nyilvantartas/lending.html', context)


def detail(request, lending_id):
	lending = Lending.objects.get(pk=lending_id)
	context = {
		'lending': lending,
	}
	return render(request, 'nyilvantartas/detail.html', context)

konyvtar/nyilvantartas/templates/nyilvantartas/detail.html
<p>Kölcsönző neve: {{lending.user}}</p>
<p>Kölcsönzött könyv címe: {{lending.book}}</p>
<p>Kölcsönzés időpontja: {{lending.lending_date}}</p>

konyvtar/nyilvantartas/templates/nyilvantartas/index.html
{% if latest_lending_list %}
    <ul>
    {% for lending in latest_lending_list %}
        <li><a href="{% url 'nyilvantartas:detail' lending.id %}">{{ lending.user }} | {{lending.book}} | {{lending.lending_date}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nincsenek kölcsönzések.</p>
{% endif %}

konyvtar/nyilvantartas/templates/nyilvantartas/lending.html
<h1>Kölcsönzés felvétele</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'nyilvantartas:lending' %}" method="post">
{% csrf_token %}
Felhasználó kiválasztása:
<select name="user">
{% for user in users %}
    <option value="{{ user.id }}">{{ user }} - {{ user.email }}</option>
{% endfor %}
</select>
<br><br>

Könyv kiválasztása:
<select name="book">
{% for book in books %}
    {% if book.btype != '0w' %}
        <option value="{{ book.id }}">{{ book.title }} - {{ book.publisher }} - {{ book.year }}</option>
    {% endif %}
{% endfor %}
</select>
<br><br>
<!--
Dátum kiválasztása:
<input type="text" placeholder="éééé-hh-nn óó:pp:mm" name=lending_date>
<br><br>
-->
<input type="submit" name="submit" value="Felvétel" />
</form>